export enum ActivityAction {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  UNASSIGNED = 'UNASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  COMPLETED = 'COMPLETED',
  COMMENTED = 'COMMENTED',
  REPLIED = 'REPLIED',
}
